// Coordinates are [longitude, latitude] in WGS84. An approximate marker is
// explicitly identified in the interface; it must never be used for navigation.
export const places = [
  { id: 'tata', name: '塔塔秘境', region: '巴音郭楞 · 尉犁', type: '沙漠与胡杨', group: '自然', coord: [86.55, 40.78], precision: '范围标注', zoom: 10, subtitle: '罗布湖、沙丘与塔里木河', note: '尉犁县 G218 887 公里处。景区范围较大，锚点仅用于总览。', locationSource: 'https://www.yuli.gov.cn/xjylx/c111274/202505/d0a0203752be47169f808bcc1f658e65.shtml' },
  { id: 'tomur', name: '温宿托木尔大峡谷', region: '阿克苏 · 温宿', type: '峡谷', group: '自然', coord: [80.689559, 41.633439], precision: '景区附近', zoom: 11, subtitle: '赭红峡谷与盐丘地貌', note: '亦称天山托木尔景区大峡谷。', locationSource: 'https://wlt.xinjiang.gov.cn/wlt/c112782/202511/4bf442dcfab84b578dcff45240ce3824.shtml' },
  { id: 'oytakh', name: '奥依塔克红山峡谷', region: '克州 · 阿克陶', type: '红山峡谷', group: '自然', coord: [75.49382, 38.94759], precision: '景区范围', zoom: 11, subtitle: '红层山体与高原河谷', note: '以奥依塔克红山谷附近地貌作范围锚点。', locationSource: 'https://mapcarta.com/W1428173527' },
  { id: 'chapuqihai', name: '恰甫其海', region: '伊犁 · 巩留', type: '湖泊', group: '湖泊', coord: [82.42814, 43.2331], precision: '观景点', zoom: 10, subtitle: '特克斯河上的蓝色水面', note: '也常被写作“恰普其海”；锚点是湖岸观景点。', locationSource: 'https://mapcarta.com/N12925114901' },
  { id: 'zhaosu', name: '昭苏玉湖', region: '伊犁 · 昭苏', type: '高山湖泊', group: '湖泊', coord: [81.053, 42.731], precision: '湖区范围', zoom: 11, subtitle: '冰川融水汇成的玉色湖泊', note: '湖区面积较大，锚点为湖区中段。', locationSource: 'https://www.amap.com/place/B0JR0AS3WC' },
  { id: 'huludao', name: '葫芦岛', region: '巴音郭楞 · 尉犁', type: '胡杨与湿地', group: '自然', coord: [86.65, 40.53], precision: '范围标注', zoom: 10, subtitle: '沙漠里的水上胡杨', note: '尉犁县古勒巴格乡 G218 921 公里处，并非辽宁葫芦岛。锚点仅用于总览。', locationSource: 'https://www.yuli.gov.cn/xjylx/c111274/202505/d0a0203752be47169f808bcc1f658e65.shtml' },
  { id: 'jiangbulake', name: '江布拉克', region: '昌吉 · 奇台', type: '草原与麦田', group: '自然', coord: [89.73849, 43.65763], precision: '景区锚点', zoom: 11, subtitle: '起伏麦海与天山山脊', note: '标在江布拉克景区锚点；不同观景点分布在更广区域。', locationSource: 'https://mapcarta.com/N10794987305' },
  { id: 'yiwanquan', name: '一万泉', region: '昌吉 · 奇台', type: '草原与林地', group: '自然', coord: [89.76195, 43.56841], precision: '景区锚点', zoom: 11, subtitle: '江布拉克附近的山地草原', note: '一万泉风景区，与江布拉克相邻。', locationSource: 'https://mapcarta.com/N8909660880' },
  { id: 'baihaba', name: '白哈巴村', region: '阿勒泰 · 哈巴河', type: '村落', group: '人文', coord: [86.781, 48.694], precision: '村落附近', zoom: 13, subtitle: '山谷里的木屋与白桦林', note: '锚点标在村落范围；边境地区请以当地要求为准。', locationSource: 'https://ditu.amap.com/place/B0FFHA1OK9' },
  { id: 'haxiong', name: '哈熊沟', region: '乌鲁木齐 · 米东', type: '山谷森林', group: '自然', coord: [87.985, 43.824], precision: '沟谷范围', zoom: 11, subtitle: '天山北坡的林间溪谷', note: '乌鲁木齐米东区哈熊沟；锚点为沟谷范围。', locationSource: 'https://ditu.amap.com/place/B0FFJZ6LVP' },
  { id: 'muji', name: '木吉湿地泥火山', region: '克州 · 阿克陶', type: '高原湿地', group: '自然', coord: [74.499, 39.001], precision: '火山群附近', zoom: 11, subtitle: '帕米尔之眼与冷火山群', note: '以木吉乡火山附近作锚点，火山口与湿地分布在更广区域。', locationSource: 'https://www.amap.com/place/B0FFI8RGZ6' },
  { id: 'baisha', name: '白沙湖 · 布伦口', region: '克州 · 阿克陶', type: '高原湖泊', group: '湖泊', coord: [74.97811, 38.69106], precision: '南岸景区', zoom: 11, subtitle: '白沙山与湛蓝湖水', note: '这里指阿克陶布伦口白沙湖，不是阿勒泰地区的同名景点。', locationSource: 'https://mapcarta.com/W1428165423' },
  { id: 'xiji', name: '中国西极石碑', region: '克州 · 乌恰', type: '地标', group: '人文', coord: [73.979, 39.731], precision: '地标附近', zoom: 13, subtitle: '西端山口的地理标记', note: '位于吉根乡方向，锚点参考高德位置。', locationSource: 'https://www.amap.com/place/B0JUO7I1MY' },
  { id: 'shache', name: '莎车老城', region: '喀什 · 莎车', type: '古城街巷', group: '人文', coord: [77.25477, 38.41517], precision: '老城片区', zoom: 14, subtitle: '叶尔羌的街巷与历史建筑', note: '老城是片区，锚点取莎车历史文化旅游景区。', locationSource: 'https://www.shache.gov.cn/scx/c125664/202505/b12dd32cca16434d88009746fa4dff96.shtml' },
  { id: 'kashgar', name: '喀什古城', region: '喀什 · 喀什市', type: '古城街巷', group: '人文', coord: [75.99197, 39.47233], precision: '古城片区', zoom: 15, subtitle: '门洞、巴扎与交错小巷', note: '古城范围较大，锚点取开放街区内的地图标注。', locationSource: 'https://mapcarta.com/W1279200258' },
  { id: 'gaotai', name: '高台民居', region: '喀什 · 喀什市', type: '历史街区', group: '人文', coord: [76.00002, 39.47021], precision: '街区锚点', zoom: 15, subtitle: '土黄色的台地民居与手工艺', note: '与喀什古城相距很近，可继续放大查看各自街巷。部分摄影作品记录的是历史面貌。', locationSource: 'https://mapcarta.com/W1279200488' },
  { id: 'bosten', name: '博斯腾湖', region: '巴音郭楞 · 博湖', type: '湖泊', group: '湖泊', coord: [86.96, 41.96], precision: '湖区范围', zoom: 10, subtitle: '芦苇湿地与辽阔湖面', note: '面积很大的湖泊，锚点仅表示湖区；图片可能来自不同岸线。', locationSource: 'https://www.openstreetmap.org/search?query=Bosten%20Lake' },
  { id: 'luobu', name: '罗布人村寨', region: '巴音郭楞 · 尉犁', type: '沙漠村寨', group: '人文', coord: [86.111, 41.086], precision: '景区游客中心附近', zoom: 12, subtitle: '沙丘、胡杨与塔里木河', note: '锚点邻近景区游客中心，游览范围较大。', locationSource: 'https://www.amap.com/place/B03E40MBXH' },
  { id: 'qiuci', name: '龟兹乐舞', region: '阿克苏 · 库车', type: '文化主题', group: '人文', coord: [82.964, 41.718], precision: '城市主题锚点', zoom: 13, subtitle: '以库车为线索的乐舞文化', note: '龟兹乐舞是一项文化主题，不是单一景点；地图锚点放在库车城区。', locationSource: 'https://www.openstreetmap.org/search?query=Kuqa' },
  { id: 'kizil', name: '克孜尔千佛洞', region: '阿克苏 · 拜城', type: '石窟', group: '人文', coord: [82.50286, 41.77718], precision: '石窟锚点', zoom: 14, subtitle: '岩壁上的龟兹石窟艺术', note: '锚点取石窟景区；洞窟内部摄影须遵守现场规定。', locationSource: 'https://mapcarta.com/N6989587788' }
];

export const groups = ['全部', '自然', '湖泊', '人文'];
